### ISSUE TITLE
Fire / Parachute games

### ISSUE THREAD

**Issue by pyrsmk** [BdR76/lcdgame.js#1]
Hi,

Congrats for your work !

I would love to be able to play to Fire and Parachute games some day. I find them really great and they have a big place in my child hood.

Cheers

**Comment by BdR76** [comment]
Thanks for the nice message :) Adding games is still quite some work, especially figuring out the timing and rules for the game. Do you have the Fire and Parachute devices? If so, you can help by taking photos and pre-processing the segments in a GIMP image, see the utils page for more info.

Btw the Parachute game is playable at pica-pic, see page here http://pica-pic.com/parachute/

**Comment by pyrsmk** [comment]
Sorry, I don't have any of those, and they're quite expensive on the market :p

Anyway, thanks for the link, I will try it!
